#[source.crates-io]
#replace-with = "vendored-sources"

#[source.vendored-sources]
#directory = "vendor"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
ar = "aarch64-linux-gnu-ar"

# Указываем системные библиотеки для AArch64
[target.aarch64-unknown-linux-gnu.env]
PKG_CONFIG_PATH = "/usr/lib/aarch64-linux-gnu/pkgconfig"
PKG_CONFIG_SYSROOT_DIR = "/usr/aarch64-linux-gnu"

[build]
target = "x86_64-unknown-linux-gnu"  # по умолчанию компилировать для x86_64
